[package]
name = "autorun-ipc"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
interprocess = { workspace = true }
nanoserde = { workspace = true }
autorun-types = { workspace = true }
