[package]
name = "autorun-core"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
serde = { workspace = true }
cap-std = { workspace = true }
anyhow = { workspace = true }
autorun-lua = { workspace = true }

nestify = "0.3.3"
toml = "0.9.5"
