[package]
name = "autorun-plugin-sys"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
autorun-core = { workspace = true }

libloading = { workspace = true }
