[package]
name = "autorun-env"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
thiserror = { workspace = true }
libloading = { workspace = true }
anyhow = { workspace = true }
retour = { workspace = true }
cap-std = { workspace = true }
rand = "0.8.5"

autorun-core = { path = "../autorun-core" }
autorun-types = { path = "../autorun-types" }
autorun-lua = { path = "../autorun-lua" }
autorun-log = { path = "../autorun-log" }
autorun-jit = { path = "../autorun-jit" }
autorun-luajit = { path = "../autorun-luajit" }
autorun-interfaces = { path = "../autorun-interfaces" }
autorun-scan = { path = "../autorun-scan" }
