[package]
name = "autorun-env"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
thiserror = { workspace = true }
libloading = { workspace = true }
anyhow = { workspace = true }
retour = { workspace = true }
cap-std = { workspace = true }
rand = "0.8.5"

autorun-core = { workspace = true }
autorun-types = { workspace = true }
autorun-lua = { workspace = true }
autorun-log = { workspace = true }
autorun-jit = { workspace = true }
autorun-luajit = { workspace = true }
autorun-interfaces = { workspace = true }
