[package]
name = "autorun-jit"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
retour = { workspace = true }
autorun-core = { workspace = true }
autorun-types = { workspace = true }
autorun-lua = { workspace = true }
autorun-log = { workspace = true }

region = "3.0.2"
