[package]
name = "autorun-interfaces"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
thiserror = { workspace = true }
libloading = { workspace = true }

autorun-types = { workspace = true }
