[package]
name = "autorun-plugin-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
autorun-lua = { workspace = true }
autorun-interfaces = { workspace = true }
autorun-env = { workspace = true }
autorun-core = { workspace = true }
